version: '3.1'

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: barriga
    ports:
      - 5433:5432